apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/your-org/devops-challenge-api-gateway
    newTag: stable
  - name: ghcr.io/your-org/devops-challenge-user-service
    newTag: stable
patches:
  - target:
      kind: ConfigMap
      name: app-config
    patch: |-
      - op: replace
        path: /data/LOG_LEVEL
        value: info