apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: devops-challenge
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: api-gateway
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
