apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: devops-challenge
  labels:
    app: user-service
    component: backend
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
  sessionAffinity: None
