apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-challenge
  labels:
    app: devops-challenge
data:
  # API Gateway configuration
  API_GATEWAY_PORT: "3000"
  USER_SERVICE_URL: "http://user-service:3001"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  
  # User Service configuration
  USER_SERVICE_PORT: "3001"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
