apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  API_GATEWAY_PORT: "3000"
  USER_SERVICE_PORT: "3001"
  USER_SERVICE_URL: "http://user-service:3001"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
  API_GATEWAY_METRICS_PREFIX: "api_gateway_"
  USER_SERVICE_METRICS_PREFIX: "user_service_"
