apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-gateway-deployment.yaml
  - api-gateway-service.yaml
  - user-service-deployment.yaml
  - user-service-service.yaml
  - redis-statefulset.yaml
  - redis-service.yaml
  - configmap.yaml
  - secret.yaml
  - hpa-api-gateway.yaml
  - hpa-user-service.yaml
  - networkpolicy-api-gateway.yaml
  - networkpolicy-user-service.yaml
  - networkpolicy-redis.yaml
