apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-api-gateway.yaml
  - configmap-user-service.yaml
  - secret-redis.yaml
  - deployment-api-gateway.yaml
  - service-api-gateway.yaml
  - deployment-user-service.yaml
  - service-user-service.yaml
  - deployment-redis.yaml
  - service-redis.yaml
  - hpa-api-gateway.yaml
  - hpa-user-service.yaml
  - networkpolicy-user-service.yaml
  - networkpolicy-redis.yaml
