apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-challenge-dev
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: patch-deployments.yaml
  - path: patch-hpa.yaml
secretGenerator:
  - name: app-secrets
    behavior: replace
    literals:
      - REDIS_PASSWORD=dev-password
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: ghcr.io/example/devops-challenge/api-gateway
    newName: devops-challenge/api-gateway
    newTag: local
  - name: ghcr.io/example/devops-challenge/user-service
    newName: devops-challenge/user-service
    newTag: local
