apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base configuration
resources:
  - ../../base

labels:
  - pairs:
      environment: dev

patches:
  - path: patches/replica-count.yaml
  - path: patches/resources.yaml
  - path: patches/configmap.yaml

# dev (will be overridden by CI/CD)
images:
  - name: devops-challenge/api-gateway
    newTag: dev-latest
  - name: devops-challenge/user-service
    newTag: dev-latest
