apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-challenge

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

# Development-specific patches
patchesStrategicMerge:
  - replica-patch.yaml
  - resource-patch.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug

images:
  - name: devops-challenge/api-gateway
    newTag: dev
  - name: devops-challenge/user-service
    newTag: dev
