name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - solution/ricardolopez010
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build API Gateway
        run: docker build -t ghcr.io/${{ github.actor }}/api-gateway:latest ./apps/api-gateway

      - name: Build User Service
        run: docker build -t ghcr.io/${{ github.actor }}/user-service:latest ./apps/user-service

      - name: Run tests (api-gateway)
        run: |
          cd apps/api-gateway
          npm install
          npm test

      - name: Run tests (user-service)
        run: |
          cd apps/user-service
          npm install
          npm test

      - name: Push images
        run: |
          docker push ghcr.io/${{ github.actor }}/api-gateway:latest
          docker push ghcr.io/${{ github.actor }}/user-service:latest
